const fs = require('fs');
const path = require('path');

const subjects = [
  "Seorang walikota", "Sebuah perusahaan multinasional", "Seorang dokter bedah", 
  "Seorang aktivis lingkungan", "Seorang mahasiswa", "Seorang janda miskin", 
  "Seorang hacker remaja", "Seorang polisi patroli", "Seorang guru honorer", "Seorang pengusaha properti"
];

const contexts = [
  "menghadapi krisis finansial yang parah", "diancam oleh mafia lokal", "menemukan celah dalam undang-undang",
  "tidak menyadari bahwa aturan telah berubah", "berusaha menyelamatkan nyawa seseorang", "terjebak dalam kontrak baku yang merugikan",
  "mengalami diskriminasi sistemik", "dipaksa oleh atasan untuk berbohong", "membela diri dari serangan mematikan", "mencoba mengungkap korupsi besar"
];

const actions = [
  "menggelapkan dana pajak sebesar 500 juta", "meretas sistem bank untuk membagikan uang ke panti asuhan", "menolak memberikan pelayanan publik",
  "membangun pabrik di atas tanah sengketa", "menyebarkan dokumen rahasia negara ke publik", "membunuh penyerangnya menggunakan senjata api ilegal",
  "melanggar kontrak kerja sepihak", "melakukan pencemaran nama baik di media sosial", "memalsukan tanda tangan untuk mencairkan asuransi", "menelantarkan kewajiban hukumnya"
];

const dilemmas = [
  "Secara hukum positif tindakan ini jelas pidana, namun secara moral ia dianggap pahlawan.",
  "Undang-undang melarangnya, tetapi asas kemanusiaan sangat membenarkannya.",
  "Tidak ada aturan yang secara eksplisit melarangnya, namun publik merasa ini sangat tidak adil.",
  "Hukum adat membenarkannya, tetapi hukum negara menjatuhkan vonis berat.",
  "Prosedur formal dilanggar, tetapi kebenaran materiil justru terungkap karenanya."
];

const consequencesA = [
  { action: "Terapkan Hukum Positif (Teks UU)", consequence: "Kepastian hukum terjaga, namun rasa keadilan masyarakat terluka.", keadilan: 10, kepastian: 95, kemanfaatan: 20, alignmentShift: 20 },
  { action: "Hukum Maksimal demi Efek Jera", consequence: "Ketertiban umum terjamin, tapi dianggap kejam.", keadilan: 30, kepastian: 90, kemanfaatan: 60, alignmentShift: 30 },
  { action: "Ikuti Preseden / Yurisprudensi", consequence: "Hukum dapat ditebak, walau mungkin sudah usang.", keadilan: 40, kepastian: 95, kemanfaatan: 50, alignmentShift: 15 },
];

const consequencesB = [
  { action: "Bebaskan (Keadilan Substantif)", consequence: "Keadilan tercapai, namun kepastian hukum menjadi goyah.", keadilan: 95, kepastian: 10, kemanfaatan: 80, alignmentShift: -25 },
  { action: "Gunakan Asas Diskresi / Ekuitas", consequence: "Hukum beradaptasi dengan manusia, namun rentan penyalahgunaan.", keadilan: 85, kepastian: 30, kemanfaatan: 90, alignmentShift: -20 },
  { action: "Hukuman Percobaan / Restorative", consequence: "Pemulihan sosial terjadi, namun ada pihak yang merasa kurang tegas.", keadilan: 90, kepastian: 40, kemanfaatan: 85, alignmentShift: -15 },
];

function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

const levels = 8;
const islandsPerLevel = 10;
const questionsPerIsland = 3;

let caseDataCode = `// Generated by generate-cases.js
export const getQuestionsForIsland = (islandId: string) => {
  const cases: Record<string, any[]> = {\n`;

let globalCounter = 1;

for (let lvl = 1; lvl <= levels; lvl++) {
  for (let isl = 1; isl <= islandsPerLevel; isl++) {
    const islandId = `${lvl}-${isl}`;
    let islandQuestions = [];
    
    for (let q = 1; q <= questionsPerIsland; q++) {
      const subject = getRandom(subjects);
      const context = getRandom(contexts);
      const action = getRandom(actions);
      const dilemma = getRandom(dilemmas);
      
      const optA = getRandom(consequencesA);
      const optB = getRandom(consequencesB);

      islandQuestions.push(`
        {
          id: "CASE-${globalCounter}",
          title: "Kasus #${globalCounter}: ${subject.split(' ')[1].toUpperCase()} DILEMA",
          facts: [
            "${subject} ${context}.",
            "Sebagai akibatnya, ia ${action}.",
            "${dilemma}"
          ],
          options: [
            {
              id: "OPT-1",
              action: "${optA.action}",
              consequence: "${optA.consequence}",
              keadilan: ${optA.keadilan},
              kepastian: ${optA.kepastian},
              kemanfaatan: ${optA.kemanfaatan},
              alignmentShift: ${optA.alignmentShift}
            },
            {
              id: "OPT-2",
              action: "${optB.action}",
              consequence: "${optB.consequence}",
              keadilan: ${optB.keadilan},
              kepastian: ${optB.kepastian},
              kemanfaatan: ${optB.kemanfaatan},
              alignmentShift: ${optB.alignmentShift}
            }
          ]
        }`);
      globalCounter++;
    }
    
    caseDataCode += `    "${islandId}": [${islandQuestions.join(',')}],\n`;
  }
}

caseDataCode += `  };
  return cases[islandId] || cases["1-1"];
};
`;

fs.writeFileSync(path.join(__dirname, 'src', 'data', 'cases.ts'), caseDataCode);
console.log('Successfully generated 240 unique cases!');
